### ISSUE TITLE
README.md missing

### ISSUE THREAD

**Issue by juanluck** [cypgain/Zombie.io#10]
Welcome to the open-source community!

I appreciate your effort for developing this project using git. I will certainly take this into account when evaluating your work. Although not strictly necessary, it is highly recommended that a github project has a README.md file in the root folder with explanations about the project itself. 

As this is all about learning, I would encourage you to write a short README.md file. That will teach you two things:

- How to write a README.md file
- How to deal with issues in your repository

Cheers!

**Comment by cypgain** [comment]
First of all, Thanks.

I didn't notice that we didn't created a README.md before.

That's solved now.
